#!/bin/bash
# FieldPro Development Environment Setup
# Run this once after cloning the repository.

set -euo pipefail

# ──────────────────────────────────────────
# Color helpers
# ──────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

info()    { echo -e "${BLUE}[INFO]${NC} $1"; }
success() { echo -e "${GREEN}[OK]${NC}   $1"; }
warn()    { echo -e "${YELLOW}[WARN]${NC} $1"; }
error()   { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

# ──────────────────────────────────────────
# Banner
# ──────────────────────────────────────────
echo ""
echo "  FieldPro — Development Environment Setup"
echo "  ========================================="
echo ""

# ──────────────────────────────────────────
# 1. Prerequisites
# ──────────────────────────────────────────
info "Checking prerequisites..."

check_command() {
    local cmd="$1"
    local min_version="$2"
    local install_hint="$3"
    if ! command -v "$cmd" &>/dev/null; then
        error "$cmd is not installed. $install_hint"
    fi
    success "$cmd found: $(${cmd} --version 2>&1 | head -1)"
}

check_command docker "20.x" "Install from https://docs.docker.com/get-docker/"
check_command node "18.x" "Install from https://nodejs.org/ (LTS recommended)"
check_command python3 "3.10" "Install from https://www.python.org/downloads/"

# Verify Docker daemon is running
if ! docker info &>/dev/null; then
    error "Docker daemon is not running. Please start Docker Desktop or the Docker service."
fi
success "Docker daemon is running"

# Check docker compose (v2 plugin or standalone)
if docker compose version &>/dev/null; then
    COMPOSE_CMD="docker compose"
elif docker-compose version &>/dev/null; then
    COMPOSE_CMD="docker-compose"
else
    error "docker compose is not available. Install Docker Desktop or the Compose plugin."
fi
success "Docker Compose found: $($COMPOSE_CMD version --short 2>/dev/null || echo 'ok')"

# ──────────────────────────────────────────
# 2. Environment file
# ──────────────────────────────────────────
info "Setting up environment file..."

if [ -f .env ]; then
    warn ".env already exists — skipping copy. Delete it and re-run to reset."
else
    # If running inside a git worktree, prefer the main worktree's .env so
    # developers don't have to manually copy secrets into every worktree.
    if [ -f .git ] && grep -q "gitdir:" .git 2>/dev/null; then
        MAIN_WORKTREE=$(git worktree list --porcelain | grep "^worktree" | head -1 | awk '{print $2}')
        if [ -f "$MAIN_WORKTREE/.env" ]; then
            cp "$MAIN_WORKTREE/.env" .env
            success "Worktree detected — copied .env from main worktree"
        elif [ -f "$MAIN_WORKTREE/.env.example" ]; then
            cp "$MAIN_WORKTREE/.env.example" .env
            success "Worktree detected — copied .env.example from main worktree → .env"
        fi
    fi

    if [ ! -f .env ]; then
    if [ -f .env.example ]; then
        cp .env.example .env
        success "Copied .env.example → .env"
    else
        warn ".env.example not found. Creating a minimal .env for local dev..."
        cat > .env << 'EOF'
# FieldPro — Local Development Environment
# ==========================================
# Generated by scripts/setup.sh

# --- Application ---
ENVIRONMENT=development
SECRET_KEY=local-dev-secret-key-change-in-production-please
REFRESH_SECRET_KEY=local-dev-refresh-key-change-in-production-please
DEBUG=true

# --- Database ---
POSTGRES_DB=fieldpro_dev
POSTGRES_USER=fieldpro
POSTGRES_PASSWORD=fieldpro_dev_password
DATABASE_URL=postgresql+asyncpg://fieldpro:fieldpro_dev_password@postgres:5432/fieldpro_dev

# --- Redis ---
REDIS_URL=redis://redis:6379

# --- Email (MailHog for local dev) ---
SMTP_HOST=mailhog
SMTP_PORT=1025
SMTP_TLS=false
SMTP_USER=
SMTP_PASSWORD=
EMAILS_FROM_EMAIL=noreply@fieldpro.local
EMAILS_FROM_NAME=FieldPro

# --- Storage ---
STORAGE_BACKEND=local
LOCAL_STORAGE_PATH=/app/uploads

# --- Frontend ---
NEXT_PUBLIC_API_URL=http://localhost:8000
NEXT_PUBLIC_APP_URL=http://localhost:3000

# --- pgAdmin ---
PGADMIN_EMAIL=admin@fieldpro.local
PGADMIN_PASSWORD=admin
EOF
        success "Created minimal .env"
    fi
    fi  # end if [ ! -f .env ]
fi

echo ""
warn "Review .env and update any values before continuing."
echo ""
read -r -p "  Press Enter to continue (or Ctrl+C to abort and edit .env first)..."
echo ""

# ──────────────────────────────────────────
# 3. Build Docker images
# ──────────────────────────────────────────
info "Building Docker images (this may take a few minutes on first run)..."
$COMPOSE_CMD build --parallel
success "Docker images built"

# ──────────────────────────────────────────
# 4. Run database migrations
# ──────────────────────────────────────────
info "Starting database..."
$COMPOSE_CMD up -d postgres redis
sleep 5   # give postgres a moment to accept connections

info "Running Alembic migrations..."
$COMPOSE_CMD run --rm backend alembic upgrade head
success "Database migrations applied"

# ──────────────────────────────────────────
# 5. Seed data
# ──────────────────────────────────────────
info "Seeding development data..."
$COMPOSE_CMD run --rm backend python scripts/seed_data.py
success "Seed data loaded"

# ──────────────────────────────────────────
# 6. Start all services
# ──────────────────────────────────────────
info "Starting all services..."
$COMPOSE_CMD up -d
sleep 3

# ──────────────────────────────────────────
# 7. Health check
# ──────────────────────────────────────────
info "Waiting for backend health check..."
MAX_RETRIES=15
RETRY=0
until curl -sf http://localhost:8000/health &>/dev/null; do
    RETRY=$((RETRY + 1))
    if [ $RETRY -ge $MAX_RETRIES ]; then
        warn "Backend did not become healthy within timeout. Check logs: docker compose logs backend"
        break
    fi
    sleep 2
done

if curl -sf http://localhost:8000/health &>/dev/null; then
    success "Backend is healthy"
fi

# ──────────────────────────────────────────
# 8. Summary
# ──────────────────────────────────────────
echo ""
echo -e "${GREEN}  Setup complete!${NC}"
echo ""
echo "  Access URLs"
echo "  ─────────────────────────────────────────"
echo "  Frontend       http://localhost:3000"
echo "  Backend API    http://localhost:8000"
echo "  API Docs       http://localhost:8000/docs"
echo "  pgAdmin        http://localhost:5050"
echo "  MailHog        http://localhost:8025"
echo ""
echo "  Default login"
echo "  ─────────────────────────────────────────"
echo "  Email:     admin@demo.fieldpro.app"
echo "  Password:  Admin123!"
echo ""
echo "  Useful commands"
echo "  ─────────────────────────────────────────"
echo "  docker compose logs -f backend     # stream backend logs"
echo "  docker compose logs -f frontend    # stream frontend logs"
echo "  docker compose down                # stop all services"
echo "  docker compose ps                  # show service status"
echo ""
